---
title: "Análisis Espacio-Temporal de Homicidios en Ecuador"
subtitle: "Evaluación de Recurrencia y Relación con Amenidades Urbanas (2014-2026)"
author: "Daniel Lara Del Salto"
date: last-modified
lang: es
format:
  html:
    toc: true
    toc-depth: 3
    theme: cosmo
    code-fold: true
    number-sections: true
    self-contained: true
execute:
  echo: true
  warning: false
  message: false
editor: visual
---

```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(sf)
library(leaflet)
library(leaflet.extras)
library(htmlwidgets)
library(patchwork)
library(rnaturalearth)
library(osmdata)

# --- PARÁMETROS CONFIGURABLES (Cambiar aquí para adaptar el análisis) ---
crs_geo     <- 4326     # WGS84 (Latitud/Longitud ideal para mapas web)
crs_proy    <- 32717    # UTM Zona 17S (Ideal para medir distancias en metros en Ecuador)
dist_umbral <- 500      # Distancia en metros para considerar un evento "vecino"
dias_umbral <- 30       # Días de diferencia para considerar un evento "vecino"
buffer_pico <- 400      # Metros de radio para extraer amenidades en zonas críticas
# -------------------------------------------------------------------------

# =============================================================================
# 2. CARGA Y LIMPIEZA DE DATOS
# =============================================================================
# Lectura de bases
base_1 <- read.csv("mdi_homicidiosintencionales_pm_2014_2025.csv")
base_2 <- read.csv("mdi_homicidiosintencionalse_pm_2026_enero_febrer.csv")
base_cruda <- bind_rows(base_1, base_2)
rm(list=c("base_1","base_2"))

# Limpieza y filtrado espacial
base_limpia <- base_cruda %>%
  mutate(
    fecha_infraccion = as.Date(fecha_infraccion, format = "%Y/%m/%d"),
    # Reemplazar comas por puntos en coordenadas
    longitud = as.numeric(gsub(",", ".", as.character(coordenada_x))),
    latitud  = as.numeric(gsub(",", ".", as.character(coordenada_y)))
  ) %>%
  # Eliminar NAs y filtrar por el Bounding Box aproximado de Ecuador
  filter(!is.na(longitud) & !is.na(latitud)) %>%
  filter(longitud > -82 & longitud < -75) %>%
  filter(latitud > -6 & latitud < 2)
```

## INTRODUCCIÓN

### Problemática

Ecuador enfrenta una escalada de violencia letal sin precedentes desde 2021. El análisis de los datos oficiales revela que estos homicidios no ocurren de forma aleatoria, sino que exhiben un agudo comportamiento de "contagio" espacio-temporal, donde un evento violento desencadena rápidamente otros en su entorno inmediato, formando *hot spots* altamente volátiles.

¿En qué medida la proximidad espacial a específicos nodos o amenidades urbanas determina la intensidad de recurrencia de los homicidios en las zonas de mayor riesgo del país?

### Descripción de los Datos

El presente análisis se fundamenta en los registros oficiales de **Homicidios Intencionales**, obtenidos del portal de **Datos Abiertos Ecuador**. La base de datos original se estructuró a partir de la consolidación de dos fuentes: la información histórica que abarca el periodo **2014 - 2025** y la actualización más reciente que cubre **enero y febrero de 2026**. Se cuenta con **31892 observaciones** y **35 variables** que describen el fenómeno criminal en múltiples dimensiones:

1.  **Dimensión Espacial y Administrativa**

    - Geografía Policial y Política: zona, subzona, distrito, circuito, subcircuito, provincia y cantón.

    - Entorno del Suceso: area_hecho, lugar, tipo_lugar

    - Geolocalización: longitud, latitud.

2.  **Dimensión Temporal**

    - fecha_infracción (YYYY-MM-DD), hora_infraccion (HH:MM:SS)

3.  **Dimensión Criminológica y Contextual**

    - Clasificación del Delito: tipo_muerte

    - Mecanismo: arma, tipo_arma

    - Causa y Motivación: presunta_motivacion, presun_motiva_observada, probable_causa_motivada

4.  **Perfil Demográfico de la Víctima**

    - Características sociodemográficas: edad, sexo, genero, etnia, estado_civil, nacionalidad, instruccion, discapacidad y profesion_registro_civil

## Datos

### Ocurrencia de los datos
